# Generated by Django 5.1.2 on 2025-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummarySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('profiles_fetched', models.IntegerField(default=0)),
                ('profiles_visited', models.IntegerField(default=0)),
                ('profiles_matched', models.IntegerField(default=0)),
                ('messages_sent', models.IntegerField(default=0)),
                ('deleted_users', models.IntegerField(default=0)),
                ('responses_received', models.IntegerField(default=0)),
                ('already_sent', models.IntegerField(default=0)),
                ('carry_forward_profiles', models.IntegerField(default=0)),
                ('carry_forward_messages', models.IntegerField(default=0)),
                ('time_spent', models.CharField(default='0h 0m', max_length=10)),
            ],
        ),
    ]
