# Generated by Django 5.1.2 on 2025-03-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SummarySession',
        ),
    ]
